name: Build Container Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build . --file Containerfile --tag wrt_builder:$(date +%s)
